@host = http://localhost:5000

GET {{host}}/api/health
Accept: application/json

###

GET {{host}}/api/books
Accept: application/json

###

GET {{host}}/api/books/test_kitap/status
Accept: application/json

###

GET {{host}}/api/books/test_kitap/export/status
Accept: application/json

###
